### ISSUE TITLE
Develop AXI memory test plan

### ISSUE THREAD

**Issue by coder-daemon** [coder-daemon/AXI_memory#13]

**Comment by Ardur0** [comment]
[test plan.xlsx](https://github.com/user-attachments/files/16623918/test.plan.xlsx)
8 test cases have been passed ,will cover the rest soon.
also this uploaded in suprith's branch

**Comment by coder-daemon** [comment]
Looks like @Ardur0 is really on a roll lately. Hope he keeps it up

**Comment by photonicray** [comment]
all the test cases are passed

[test.plan.ods](https://github.com/user-attachments/files/16643292/test.plan.ods)
